# Generated by Django 3.0.6 on 2020-05-11 02:35

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_requirement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grad_date',
            field=models.CharField(default='S20', max_length=3, validators=[courses.models.validate_semester]),
            preserve_default=False,
        ),
    ]
